### ISSUE TITLE
[Bug] Cannot install dbt-postgres with pip

### ISSUE THREAD

**Issue by talenelat** [dbt-labs/dbt-postgres#132]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Cannot install package with pip.

### Expected Behavior

`pip install dbt-postgres` should work.

### Steps To Reproduce

1. Create virtual environment;
2. `pip install dbt-postgres`

### Relevant log output

```shell
Collecting logbook<1.6,>=1.5 (from dbt-core>=1.8.0a1->dbt-postgres)
  Using cached Logbook-1.5.3.tar.gz (85 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/Users/krusty/.pyenv/versions/3.12.0/envs/data/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/krusty/.pyenv/versions/3.12.0/envs/data/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/krusty/.pyenv/versions/3.12.0/envs/data/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/fk/n0zsqk0x5qv7pfdr_lqcbc0w0000gn/T/pip-build-env-56pe_3bx/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/fk/n0zsqk0x5qv7pfdr_lqcbc0w0000gn/T/pip-build-env-56pe_3bx/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/fk/n0zsqk0x5qv7pfdr_lqcbc0w0000gn/T/pip-build-env-56pe_3bx/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/fk/n0zsqk0x5qv7pfdr_lqcbc0w0000gn/T/pip-build-env-56pe_3bx/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 64, in <module>
      ModuleNotFoundError: No module named 'setuptools.command.test'
      [end of output]
```

### Environment

```markdown
- OS: macOS
- Python: 3.12.0
- dbt-postgres: latest
```

### Additional Context

Seems like this is `setuptools` related, as others have encountered this problem: https://stackoverflow.com/questions/78806100/no-module-named-setuptools-command-test

Workaround solution (tested and it works, but this should be temporary until the packages are updated): https://github.com/pypa/setuptools/issues/4519#issuecomment-2255358015

**Comment by amychen1776** [comment]
@talenelat This is odd, I didn't have any issues on installing dbt-postgres via pip. I think the reason why this failed for you is we just recently started to support python 3.12 https://github.com/dbt-labs/dbt-postgres/pull/135 

I'm going to close this issue for now but please reopen if you see this again.
